### ISSUE TITLE
[ENH] Network Explorer improvements

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-network#16]
1.) Network Explorer should display legend if coloring by attribute.
2.) Network Explorer should allow saving images (I thought this was working already??) and Report (while at it).
3.) Widget crashes when coloring by sparse attributes. NaN should probably be white and/or add warning.
4.) Widget's output should be compatible with Word Enrichment (wishlist, but so great for text analysis!). @nikicc

**Comment by ajdapretnar** [comment]
5.) Widget crashes when setting the size by string attribute. (I don't even know why this if offered, it shouldn't be.)

**Comment by kernc** [comment]
> 2.) Network Explorer should allow saving images and Report.
> 5.) Widget crashes when setting the size by string attribute. (I don't even know why this if offered, it shouldn't be.)

Fixed in https://github.com/biolab/orange3-network/pull/14

> 3.) Widget crashes when coloring by sparse attributes. NaN should probably be white and/or add warning.

Deferred until after pandas.

**Comment by ajdapretnar** [comment]
> Fixed in #14 

No entirely. Now the images can be saved, but they still don't appear in the report.

**Comment by jerneju** [comment]
> 1.) Network Explorer should display legend if coloring by attribute.

+1

**Comment by ajdapretnar** [comment]
Images cannot be saved, again. Also console is reporting many QPainter events when I try to save images through Save Image button. This should really work, IMHO.

**Comment by kernc** [comment]
Supposing this [had worked before](https://github.com/biolab/orange3-network/pull/14#issuecomment-268748631), can you perhaps [`git-bisect`](http://webchick.net/node/99) to the offending change.

**Comment by ajdapretnar** [comment]
I tried, but checking out commits where this _supposedly_ worked, I got even worse errors than just not being able to save an image.
I.e.: AttributeError: 'Graph' object has no attribute 'edges_iter'
Don't understand why this is there.

**Comment by jerneju** [comment]
@ajdapretnar 
> I.e.: AttributeError: 'Graph' object has no attribute 'edges_iter'

This is an old error and it is expected to be resolved tomorrow.

**Comment by kernc** [comment]
The error you encounter is due to networkx 2.0 changed API. Our use of it was fixed recently but not in old commits you check out. https://github.com/biolab/orange3-network/issues/43, https://github.com/biolab/orange3-network/issues/44

**Comment by kernc** [comment]
What you can do to remedy it is `pip install -U --no-deps networkx==1.11` when you encounter the error, and back `pip install -U --no-deps networkx` when you encounter the other similar error (i.e. before vs after https://github.com/biolab/orange3-network/commit/34b1d58dbcf2d2764b33c21df6ae9360f5819a14). 😄

**Comment by janezd** [comment]
Obsoleted by #83.
